# Generated by Django 5.1 on 2024-08-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WordPuzzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('words', models.TextField(help_text='Enter the words separated by commas.')),
                ('grid_size', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
